backend:
  #name: proxy
  #proxy_url: http://localhost:8081/api/v1
  name: git-gateway
  repo: korukugashi/fne-bfc-gatsby
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

site_url: https://fne-bfc.netlify.app/
locale: 'fr'
#publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - label: "Agenda"
    name: "agenda"
    create: true
    folder: "src/pages/agenda/events"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "agenda"}
      - {label: "Date", name: "date", widget: "datetime", pickerUtc: false, dateFormat: "DD/MM/YYYY", timeFormat: "HH:mm"}
      - {label: "Titre", name: title, widget: string}
      - {label: "Lieu", name: location, widget: string}
      - {label: "Horaires / durée", name: duration, widget: string}
      - {label: "Informations complémentaires", name: "body", widget: "markdown", required: false}

  - name: "actions"
    label: "Actions (actus)"
    folder: "src/pages/nos-actions"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "action-post"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime", pickerUtc: false, dateFormat: "DD/MM/YYYY", timeFormat: "HH:mm"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image de présentation", name: "featuredimage", widget: image, required: false}
      - {label: "Article", name: "body", widget: "markdown"}
      - label: "Tags"
        name: "tags"
        widget: "relation"
        collection: "actionstags"
        searchFields: ["label"]
        valueField: "label"
        displayFields: ["label"]
        multiple: true

  - name: "programmes"
    label: "Actions (programmes)"
    folder: "src/pages/nos-actions/programmes"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "programmes"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Article", name: "body", widget: "markdown"}
      - label: "Tags (actus liées)"
        name: "tags"
        widget: "relation"
        collection: "actionstags"
        searchFields: ["label"]
        valueField: "label"
        displayFields: ["label"]
        multiple: true
  
  - label: "Tags (actions)"
    name: "actionstags"
    create: true
    folder: "src/pages/nos-actions/tags"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "actions-tags"}
      - {label: "Libellé", name: label, widget: string}
      - {name: image, label: Icône, widget: image}

  - label: "Associations régionales"
    name: "reseauassos"
    create: true
    folder: "src/pages/reseau-fne/assos"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "reseau-assos"}
      - {label: "Libellé", name: label, widget: string}
      - {label: "Lien site", name: url, widget: string, required: false}
      - {name: image, label: Logo, widget: image, required: false}
  
  - label: "Fédérations départementales"
    name: "reseaufedes"
    create: true
    folder: "src/pages/reseau-fne/fedes"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "reseau-fedes"}
      - {label: "Libellé", name: label, widget: string}
      - {label: "Lien site", name: url, widget: string, required: false}
      - {name: image, label: Logo, widget: image, required: false}
  
  - label: "Soutiens"
    name: "soutiens"
    create: true
    folder: "src/pages/soutiens/collectifs"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "soutiens"}
      - {label: "Libellé", name: label, widget: string}
      - {label: "Lien site", name: url, widget: string, required: false}
      - {name: image, label: Logo, widget: image, required: false}
  
  - name: team
    label: "Équipe"
    folder: "src/pages/qui-sommes-nous/equipe"
    fields:
      - { name: title, label: "Titre", default: "L'équipe de FNE BFC" }
      - name: admins
        label: Administrateurs
        widget: list
        fields:
          - { name: name, label: "Prénom et nom de l'administrateur" }
          - { name: fonction, label: "Fonction" }
          - { name: photo, label: "Photo de l'administrateur", widget: image}
      - name: salaries
        label: Salariés
        widget: list
        fields:
          - { name: name, label: "Prénom et nom du salarié" }
          - { name: fonction, label: "Fonction" }
          - { name: photo, label: "Photo du salarié", widget: image}
  
  - label: "Documents"
    name: "documents"
    create: true
    folder: "src/pages/documentation/documents"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "documents"}
      - {label: "Date", name: "date", widget: "datetime", pickerUtc: false, dateFormat: "DD/MM/YYYY", timeFormat: "HH:mm"}
      - {label: "Titre", name: title, widget: string}
      - {label: "Fichier", name: file, widget: "file"}
  
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/qui-sommes-nous/index.md"
        label: "L'association"
        name: "association"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "association-page"}
          - {label: "Contenu de la page", name: "body", widget: "markdown"}